---
- name: Install unzip
  apt:
    name: unzip
    state: present

- name: Download SonarQube
  get_url:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.0.65466.zip
    dest: /opt/sonarqube.zip

- name: Unzip SonarQube
  unarchive:
    src: /opt/sonarqube.zip
    dest: /opt/
    remote_src: yes

- name: Rename SonarQube directory
  command: mv /opt/sonarqube-9.9.0.65466 /opt/sonarqube
  args:
    creates: /opt/sonarqube

- name: Set SonarQube permissions
  file:
    path: /opt/sonarqube
    owner: ubuntu  # Default Ubuntu EC2 user
    group: ubuntu
    recurse: yes

- name: Configure SonarQube to run as a service
  copy:
    content: |
      [Unit]
      Description=SonarQube service
      After=syslog.target network.target
      
      [Service]
      Type=forking
      ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
      ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop
      User=ubuntu
      Group=ubuntu
      Restart=always
      
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/sonarqube.service

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable and start SonarQube
  service:
    name: sonarqube
    state: started
    enabled: yes